---
date: "2016-04-27T00:00:00Z"
external_link: ""
image:
  caption: The integration of multiple studies.
  focal_point: Smart
summary: Bayesian Evidence Synthesis is a method to integrate the results of multiple studies with varying, seemingly incompatible, designs using Bayes Factors, to enhance the aggregation of scientific evidence.
tags:
- Bayesian Evidence Synthesis
title: Bayesian Evidence Synthesis
bibliography: "thesis_literature.bib"
csl: "apa-6th-edition.csl"
---

In recent years, the importance of replications has received considerable attention [e.g., @open_science_collab_2015; @baker_reproducibility_2016; @brandt_et_al_replication_2014]. However, emphasis has been placed primarily on exact, direct or close replication studies. These studies employ an identical methodology and research design as the initial study, and are thus merely concerned with the statistical reliability of the results. If these results depend on methodological flaws, inferences from all studies will lead to suboptimal or invalid conclusions [@munafo_robust_2018]. To overcome these limitations, the use of conceptual replications has been advocated [e.g., @munafo_robust_2018; @lawlor_triangulation_2017]. Specifically, conceptual replications scrutinize the extent to which the initial conclusions hold under different conditions, using varying instruments or operationalizations.

However, established methods such as (Bayesian) meta-analysis and Bayesian updating are not applicable when studies differ conceptually. This is due to the fact that these methods require that the parameter estimates (i) share a common scale, and (ii) result from analyses with identical function forms [@lipsey_wilson_2001; @sutton_bayesian_meta2001; @schonbrodt_sequential_2017]. Consequently, @kuiper_combining_2013 proposed Bayesian Evidence Synthesis (BES), which is built upon the foundation of the Bayes Factor [BF; @kass_raftery_bayes_factors_1995]. This method allows researchers to pool evidence for a specific hypothesis over multiple studies, even if the studies have seemingly incompatible designs. 

In the current project, Irene Klugkist and I aim to reveal under which circumstances BES performs inadequately. Additionally, we hope to propose adjustments to the method that improve its performance, so that an increasing number of researchers can benefit from BES.

#### References